#Start of Template
#RHugg - github.com/rhuggcode
#Notes:Cname tag is used to trigger DNS registration in route 53 via lambda/cloudwatch
#
#Start of Template
AWSTemplateFormatVersion: 2010-09-09
Description: 'v1.0 - Creates EC2 Instance'

Parameters:
  myKeyPair: 
    Description: Amazon EC2 Key Pair
    Type: AWS::EC2::KeyPair::KeyName
  mySubnetIDs: 
    Description: Subnet IDs
    Type: AWS::EC2::Subnet::Id
  InstanceTypeParameter: 
    Type: String
    Default: t2.micro
    AllowedValues: 
      - t2.micro
      - m1.small
      - m1.large
    Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.
  myDNSFQDN:
    Type: String
    Description: FQDN of server. Must in in domain.com
  mySecurityGroups:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: Select security groups to attach

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType:
        Ref: InstanceTypeParameter
      SubnetId:
        Ref: mySubnetIDs
      SecurityGroupIds:
        Ref: mySecurityGroups
      ImageId: ami-428aa838
      Tags:
        - Key: "Name"
          Value:
            Ref: myDNSFQDN
        - Key: "CName"
          Value: !Sub
          - ${VarName}.
          - { VarName: !Ref myDNSFQDN }
